services:
  db:
    image: mysql:8.0
    container_name: db_uni
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: uni_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpass
    ports:
      - "3307:3306"
    volumes:
      - db_uni_data:/var/lib/mysql

volumes:
  db_uni_data: