CREATE DATABASE IF NOT EXISTS escuela_db;
CREATE DATABASE IF NOT EXISTS crm_db;
CREATE DATABASE IF NOT EXISTS uni_db;
CREATE DATABASE IF NOT EXISTS empresa_db;

CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'adminpass';
GRANT ALL PRIVILEGES ON crm_db.* TO 'admin'@'%';
GRANT ALL PRIVILEGES ON uni_db.* TO 'admin'@'%';

CREATE USER IF NOT EXISTS 'dev_user'@'%' IDENTIFIED BY 'dev_pass123';
GRANT ALL PRIVILEGES ON empresa_db.* TO 'dev_user'@'%';

GRANT ALL PRIVILEGES ON *.* TO 'universidad'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
